export const moviesFixture = [
  {
    adult: false,
    backdrop_path: "/gMJngTNfaqCSCqGD4y8lVMZXKDn.jpg",
    genre_ids: [28, 12, 878],
    id: 640146,
    original_language: "en",
    original_title: "Ant-Man and the Wasp: Quantumania",
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    popularity: 8567.865,
    poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    release_date: "2023-02-15",
    title: "Ant-Man and the Wasp: Quantumania",
    video: false,
    vote_average: 6.5,
    vote_count: 1886,
  },
  {
    adult: false,
    backdrop_path: "/iJQIbOPm81fPEGKt5BPuZmfnA54.jpg",
    genre_ids: [16, 12, 10751, 14, 35],
    id: 502356,
    original_language: "en",
    original_title: "The Super Mario Bros. Movie",
    overview:
      "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
    popularity: 6572.614,
    poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    release_date: "2023-04-05",
    title: "The Super Mario Bros. Movie",
    video: false,
    vote_average: 7.5,
    vote_count: 1456,
  },
  {
    adult: false,
    backdrop_path: "/nDxJJyA5giRhXx96q1sWbOUjMBI.jpg",
    genre_ids: [28, 35, 14],
    id: 594767,
    original_language: "en",
    original_title: "Shazam! Fury of the Gods",
    overview:
      'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
    popularity: 4274.232,
    poster_path: "/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
    release_date: "2023-03-15",
    title: "Shazam! Fury of the Gods",
    video: false,
    vote_average: 6.9,
    vote_count: 1231,
  },
  {
    adult: false,
    backdrop_path: "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    popularity: 3365.913,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar: The Way of Water",
    video: false,
    vote_average: 7.7,
    vote_count: 7535,
  },
  {
    adult: false,
    backdrop_path: "/xwA90BwZXTh8ke3CVsQlj8EOkFr.jpg",
    genre_ids: [28, 12, 36, 18, 10752],
    id: 948713,
    original_language: "en",
    original_title: "The Last Kingdom: Seven Kings Must Die",
    overview:
      "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
    popularity: 3119.049,
    poster_path: "/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg",
    release_date: "2023-04-14",
    title: "The Last Kingdom: Seven Kings Must Die",
    video: false,
    vote_average: 7.4,
    vote_count: 232,
  },
  {
    adult: false,
    backdrop_path: "/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
    genre_ids: [18, 28],
    id: 677179,
    original_language: "en",
    original_title: "Creed III",
    overview:
      "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damian — a fighter who has nothing to lose.",
    popularity: 2856.222,
    poster_path: "/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
    release_date: "2023-03-01",
    title: "Creed III",
    video: false,
    vote_average: 7.3,
    vote_count: 1192,
  },
  {
    adult: false,
    backdrop_path: "/bT3IpP7OopgiVuy6HCPOWLuaFAd.jpg",
    genre_ids: [35, 9648, 28],
    id: 638974,
    original_language: "en",
    original_title: "Murder Mystery 2",
    overview:
      "After starting their own detective agency, Nick and Audrey Spitz land a career-making case when their billionaire pal is kidnapped from his wedding.",
    popularity: 1879.655,
    poster_path: "/s1VzVhXlqsevi8zeCMG9A16nEUf.jpg",
    release_date: "2023-03-28",
    title: "Murder Mystery 2",
    video: false,
    vote_average: 6.5,
    vote_count: 864,
  },
  {
    adult: false,
    backdrop_path: "/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
    genre_ids: [27, 53],
    id: 713704,
    original_language: "en",
    original_title: "Evil Dead Rise",
    overview:
      "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
    popularity: 1696.367,
    poster_path: "/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
    release_date: "2023-04-12",
    title: "Evil Dead Rise",
    video: false,
    vote_average: 7,
    vote_count: 207,
  },
  {
    adult: false,
    backdrop_path: "/ouB7hwclG7QI3INoYJHaZL4vOaa.jpg",
    genre_ids: [16, 10751, 14, 12, 35, 18],
    id: 315162,
    original_language: "en",
    original_title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    popularity: 1347.259,
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    release_date: "2022-12-07",
    title: "Puss in Boots: The Last Wish",
    video: false,
    vote_average: 8.3,
    vote_count: 5331,
  },
  {
    adult: false,
    backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    popularity: 1320.735,
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    title: "John Wick: Chapter 4",
    video: false,
    vote_average: 8,
    vote_count: 1211,
  },
  {
    adult: false,
    backdrop_path: "/nDmPjKLqLwWyd4Ssti8HCdhW5cZ.jpg",
    genre_ids: [28],
    id: 1048300,
    original_language: "en",
    original_title: "Adrenaline",
    overview:
      "A female FBI agent holidaying in Eastern Europe with her family gets her life upside down when her daughter is kidnapped. She has to team up with a criminal on the run to save her daughter before time runs out.",
    popularity: 1460.629,
    poster_path: "/qVzRt8c2v4gGBYsnaflXVVeQ9Lh.jpg",
    release_date: "2022-12-15",
    title: "Adrenaline",
    video: false,
    vote_average: 4,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/a2tys4sD7xzVaogPntGsT1ypVoT.jpg",
    genre_ids: [53, 35, 80],
    id: 804150,
    original_language: "en",
    original_title: "Cocaine Bear",
    overview:
      "Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.",
    popularity: 1175.491,
    poster_path: "/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
    release_date: "2023-02-22",
    title: "Cocaine Bear",
    video: false,
    vote_average: 6.4,
    vote_count: 878,
  },
  {
    adult: false,
    backdrop_path: "/54IXMMEQKlkPXHqPExWy98UBmtE.jpg",
    genre_ids: [27],
    id: 1008005,
    original_language: "es",
    original_title: "La niña de la comunión",
    overview:
      "Spain, late 1980s. Newcomer Sara tries to fit in with the other teens in this tight-knit small town in the province of Tarragona. If only she were more like her extroverted best friend, Rebe. They go out one night at a nightclub, on the way home, they come upon a little girl holding a doll, dressed for her first communion. And that's when the nightmare begins.",
    popularity: 1154.3,
    poster_path: "/sP6AO11a7jWgsmT9T8j9EGIWAaZ.jpg",
    release_date: "2023-02-10",
    title: "The Communion Girl",
    video: false,
    vote_average: 6.5,
    vote_count: 58,
  },
  {
    adult: false,
    backdrop_path: "/tFaC1Fb1sv1dALB0i9Avi76MHmn.jpg",
    genre_ids: [10751, 28, 12],
    id: 946310,
    original_language: "nl",
    original_title: "De Piraten van Hiernaast II: De Ninja's van de Overkant",
    overview:
      "The pirates feel right at home in Sandborough, but the atmosphere cools right down when the ninjas come to live in the street. After all, pirates and ninjas are sworn enemies!  While pirate captain Hector Blunderbuss struggles to get rid of his new neighbours, son Billy and ninja daughter Yuka become friends. The pirates challenge the ninjas to the ultimate battle at the village's annual hexathlon. Who will win the match? Ninjas are faster and more agile of course, but pirates are the best cheats in all of the seven seas...",
    popularity: 1159.928,
    poster_path: "/uDsvma9dAwnDPVuCFi99YpWvBk0.jpg",
    release_date: "2022-04-20",
    title: "Pirates Down the Street II: The Ninjas from Across",
    video: false,
    vote_average: 6.4,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: "/rPSJAElGxOTko1zK6uIlYnTMFxN.jpg",
    genre_ids: [80],
    id: 1104040,
    original_language: "en",
    original_title: "Gangs of Lagos",
    overview:
      "A group of friends who each have to navigate their own destiny, growing up on the bustling streets and neighborhood of Isale Eko, Lagos.",
    popularity: 1138.252,
    poster_path: "/nGwFsB6EXUCr21wzPgtP5juZPSv.jpg",
    release_date: "2023-04-07",
    title: "Gangs of Lagos",
    video: false,
    vote_average: 5.6,
    vote_count: 21,
  },
  {
    adult: false,
    backdrop_path: "/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg",
    genre_ids: [878, 12, 53, 28],
    id: 700391,
    original_language: "en",
    original_title: "65",
    overview:
      "65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.",
    popularity: 1077.09,
    poster_path: "/rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
    release_date: "2023-03-02",
    title: "65",
    video: false,
    vote_average: 6.3,
    vote_count: 763,
  },
  {
    adult: false,
    backdrop_path: "/5Y5pz0NX7SZS9036I733F7uNcwK.jpg",
    genre_ids: [27, 53],
    id: 758323,
    original_language: "en",
    original_title: "The Pope's Exorcist",
    overview:
      "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
    popularity: 1073.229,
    poster_path: "/9JBEPLTPSm0d1mbEcLxULjJq9Eh.jpg",
    release_date: "2023-04-05",
    title: "The Pope's Exorcist",
    video: false,
    vote_average: 6.5,
    vote_count: 143,
  },
  {
    adult: false,
    backdrop_path: "/m1fgGSLK0WvRpzM1AmZu38m0Tx8.jpg",
    genre_ids: [28],
    id: 842945,
    original_language: "en",
    original_title: "Supercell",
    overview:
      "Good-hearted teenager William always lived in hope of following in his late father’s footsteps and becoming a storm chaser. His father’s legacy has now been turned into a storm-chasing tourist business, managed by the greedy and reckless Zane Rogers, who is now using William as the main attraction to lead a group of unsuspecting adventurers deep into the eye of the most dangerous supercell ever seen.",
    popularity: 942.178,
    poster_path: "/gbGHezV6yrhua0KfAgwrknSOiIY.jpg",
    release_date: "2023-03-17",
    title: "Supercell",
    video: false,
    vote_average: 6.3,
    vote_count: 125,
  },
  {
    adult: false,
    backdrop_path: "/tYcmm8XtzRdcT6kliCbHuWwLCwB.jpg",
    genre_ids: [28, 80, 53],
    id: 849869,
    original_language: "ko",
    original_title: "길복순",
    overview:
      "At work, she's a renowned assassin. At home, she's a single mom to a teenage daughter. Killing? That's easy. It's parenting that's the hard part.",
    popularity: 958.517,
    poster_path: "/taYgn3RRpCGlTGdaGQvnSIOzXFy.jpg",
    release_date: "2023-02-17",
    title: "Kill Boksoon",
    video: false,
    vote_average: 6.8,
    vote_count: 184,
  },
  {
    adult: false,
    backdrop_path: "/eNJhWy7xFzR74SYaSJHqJZuroDm.jpg",
    genre_ids: [28, 878],
    id: 1033219,
    original_language: "en",
    original_title: "Attack on Titan",
    overview:
      "As viable water is depleted on Earth, a mission is sent to Saturn's moon Titan to retrieve sustainable H2O reserves from its alien inhabitants. But just as the humans acquire the precious resource, they are attacked by Titan rebels, who don't trust that the Earthlings will leave in peace.",
    popularity: 897.66,
    poster_path: "/qNz4l8UgTkD8rlqiKZ556pCJ9iO.jpg",
    release_date: "2022-09-30",
    title: "Attack on Titan",
    video: false,
    vote_average: 6.1,
    vote_count: 105,
  },
];

export const searchFixture = [
  {
    adult: false,
    backdrop_path: "/yAzC0pV1e1BzXA5NyWsGsRggOM5.jpg",
    genre_ids: [35, 28],
    id: 10535,
    original_language: "en",
    original_title: "Spy Hard",
    overview:
      "The evil Gen. Rancor has his sights set on world domination, and only one man can stop him: Dick Steele, also known as Agent WD-40. Rancor needs to obtain a computer circuit for the missile that he is planning to fire, so Steele teams up with Veronique Ukrinsky, a KGB agent whose father designed the chip. Together they try to locate the evil mastermind's headquarters, where Veronique's father and several other hostages are being held.",
    popularity: 3.1465,
    poster_path: "/yoegp9XEG4YCbJJKR0wvm0BGYpG.jpg",
    release_date: "1996-05-24",
    title: "Spy Hard",
    video: false,
    vote_average: 5.42,
    vote_count: 751,
  },
  {
    adult: false,
    backdrop_path: "/bmuTrxbPcr1nKCsV5YWWJi73PGR.jpg",
    genre_ids: [10751, 28, 35, 12, 878],
    id: 12279,
    original_language: "en",
    original_title: "Spy Kids 3-D: Game Over",
    overview:
      "Carmen's caught in a virtual reality game designed by the Kids' new nemesis, the Toymaker. It's up to Juni to save his sister, and ultimately the world.",
    popularity: 3.5825,
    poster_path: "/buA8dN4zLNr0dYBeKfHfMnEfdLE.jpg",
    release_date: "2003-07-25",
    title: "Spy Kids 3-D: Game Over",
    video: false,
    vote_average: 5.141,
    vote_count: 2347,
  },
  {
    adult: false,
    backdrop_path: "/9CqzJn0nLaDNM6QWfGkuox2Oi93.jpg",
    genre_ids: [35, 28, 12],
    id: 454992,
    original_language: "en",
    original_title: "The Spy Who Dumped Me",
    overview:
      "A couple of thirtysomething best friends unwittingly become entangled in an international conspiracy when one’s ex-boyfriend shows up at their apartment with a team of deadly assassins on his trail.",
    popularity: 3.4911,
    poster_path: "/szEKivKPOdRyogROoQIldwbMl.jpg",
    release_date: "2018-08-02",
    title: "The Spy Who Dumped Me",
    video: false,
    vote_average: 6.376,
    vote_count: 2343,
  },
  {
    adult: false,
    backdrop_path: "/qyHc9Fxgt6Szby7fmItRd9fpM6V.jpg",
    genre_ids: [36, 18, 53],
    id: 399121,
    original_language: "fr",
    original_title: "J'accuse",
    overview:
      "In 1894, French Captain Alfred Dreyfus is wrongfully convicted of treason and sentenced to life imprisonment at the Devil’s Island penal colony.",
    popularity: 3.4689,
    poster_path: "/kqlzmKVBpGz7OMWfOXlK4y1m9Uz.jpg",
    release_date: "2019-09-30",
    title: "An Officer and a Spy",
    video: false,
    vote_average: 7.073,
    vote_count: 1582,
  },
  {
    adult: false,
    backdrop_path: "/7Hfatv0lZkMyxw8UBZmiK2qSXDR.jpg",
    genre_ids: [28, 80, 53],
    id: 1535,
    original_language: "en",
    original_title: "Spy Game",
    overview:
      "On the day of his retirement, a veteran CIA agent learns that his former protégé has been arrested in China, is sentenced to die the next morning in Beijing, and that the CIA is considering letting that happen to avoid an international scandal.",
    popularity: 4.1635,
    poster_path: "/6y8M1rxjKofQCRKKe6xeV91K2Fc.jpg",
    release_date: "2001-11-18",
    title: "Spy Game",
    video: false,
    vote_average: 6.916,
    vote_count: 2320,
  },
  {
    adult: false,
    backdrop_path: "/w7TUrUUo9pKcgY7PCdm2LK6XbZB.jpg",
    genre_ids: [28, 35, 10751],
    id: 23172,
    original_language: "en",
    original_title: "The Spy Next Door",
    overview:
      "Former CIA spy Bob Ho takes on his toughest assignment to date: looking after his girlfriend's three kids, who haven't exactly warmed to their mom's beau. And when one of the youngsters accidentally downloads a top-secret formula, Bob's longtime nemesis, a Russian terrorist, pays a visit to the family.",
    popularity: 3.2022,
    poster_path: "/nJJrceb2xHGIA0irADX0JvWSIHT.jpg",
    release_date: "2010-01-15",
    title: "The Spy Next Door",
    video: false,
    vote_average: 5.877,
    vote_count: 1393,
  },
  {
    adult: false,
    backdrop_path: "/3pIqd1hgZ2xqzWEyiYp4blqE9Fi.jpg",
    genre_ids: [53, 36, 18],
    id: 522241,
    original_language: "en",
    original_title: "The Courier",
    overview:
      "Cold War spy Greville Wynne and his Russian source try to put an end to the Cuban Missile Crisis.",
    popularity: 3.1275,
    poster_path: "/zFIjKtZrzhmc7HecdFXXjsLR2Ig.jpg",
    release_date: "2020-01-24",
    title: "The Courier",
    video: false,
    vote_average: 7.03,
    vote_count: 1307,
  },
  {
    adult: false,
    backdrop_path: "/3COCz2DMRNefY4a3lfUHrNj4tl0.jpg",
    genre_ids: [10751, 35, 28, 12, 18, 14, 878],
    id: 56288,
    original_language: "en",
    original_title: "Spy Kids: All the Time in the World",
    overview:
      "Eight years after the third film, the OSS has become the world's top spy agency, while the Spy Kids department has since become defunct. Retired spy Marissa is called back into action, and to bond with her new stepchildren Rebecca and Cecil, she invites them along to stop the evil Timekeeper from taking over the world.",
    popularity: 3.576,
    poster_path: "/9pUVarhiXfCu8amjmyadzJJJITi.jpg",
    release_date: "2011-08-18",
    title: "Spy Kids: All the Time in the World",
    video: false,
    vote_average: 4.7,
    vote_count: 1050,
  },
  {
    adult: false,
    backdrop_path: "/nMEGEPQIyS30KIJpZETGpluFquJ.jpg",
    genre_ids: [28, 80, 35],
    id: 412988,
    original_language: "en",
    original_title: "The Happytime Murders",
    overview:
      "In a world where humans coexist with puppets—who are seen as lesser citizens—cast members of a beloved 1990s children's television series begin getting murdered one by one. Puppet Phil Philips, an ex-LAPD detective-turned-private eye, takes on the case at the request of his old boss in order to assist his former partner, Detective Connie Edwards.",
    popularity: 2.9624,
    poster_path: "/rWxkur51srfVnMn2QOFjE7mbq6h.jpg",
    release_date: "2018-08-22",
    title: "The Happytime Murders",
    video: false,
    vote_average: 5.8,
    vote_count: 1077,
  },
  {
    adult: false,
    backdrop_path: "/ulkWS7Atv0vv33KVCSAmNizAmJd.jpg",
    genre_ids: [878, 53],
    id: 615469,
    original_language: "en",
    original_title: "Spiderhead",
    overview:
      "A prisoner in a state-of-the-art penitentiary begins to question the purpose of the emotion-controlling drugs he's testing for a pharmaceutical genius.",
    popularity: 3.6025,
    poster_path: "/7COPO5B9AOKIB4sEkvNu0wfve3c.jpg",
    release_date: "2022-06-17",
    title: "Spiderhead",
    video: false,
    vote_average: 5.796,
    vote_count: 1722,
  },
  {
    adult: false,
    backdrop_path: "/aPVq0ZPNEzBRU3dWSQ8YNoJHk61.jpg",
    genre_ids: [28, 35],
    id: 331313,
    original_language: "en",
    original_title: "Keeping Up with the Joneses",
    overview:
      "An ordinary suburban couple finds it’s not easy keeping up with the Joneses – their impossibly gorgeous and ultra-sophisticated new neighbors – especially when they discover that Mr. and Mrs. “Jones” are covert operatives.",
    popularity: 2.7691,
    poster_path: "/yvWcTrRCzE4C2hkd2wV4erPuKCn.jpg",
    release_date: "2016-10-20",
    title: "Keeping Up with the Joneses",
    video: false,
    vote_average: 6.086,
    vote_count: 2129,
  },
  {
    adult: false,
    backdrop_path: "/7e9tSzepYj8ZNbVF9P7KJ3BLlxD.jpg",
    genre_ids: [36, 18, 10752],
    id: 1079244,
    original_language: "en",
    original_title: "Bonhoeffer: Pastor. Spy. Assassin",
    overview:
      "As the world teeters on the brink of annihilation, Dietrich Bonhoeffer joins a deadly plot to assassinate Hitler, risking his faith and fate to save millions of Jews from genocide.",
    popularity: 2.5652,
    poster_path: "/9WtImcI6k9XOcnPmSeN2Kzpf4ay.jpg",
    release_date: "2024-11-20",
    title: "Bonhoeffer: Pastor. Spy. Assassin",
    video: false,
    vote_average: 6.716,
    vote_count: 74,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [35, 28],
    id: 262866,
    original_language: "en",
    original_title: "In Security",
    overview:
      "The owners of a failing security company start robbing houses to boost business.",
    popularity: 1.9718,
    poster_path: "/kn8xtTjqTR8CgvLjDAgp5z8Eifj.jpg",
    release_date: "2014-04-28",
    title: "In Security",
    video: false,
    vote_average: 5,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: "/zVVYFN9OjiSn43RVYrzgCOu7y6r.jpg",
    genre_ids: [18, 9648, 53],
    id: 9613,
    original_language: "en",
    original_title: "Spider",
    overview:
      "A mentally disturbed man takes residence in a halfway house. His mind gradually slips back into the realm created by his illness, where he replays a key part of his childhood.",
    popularity: 2.1297,
    poster_path: "/zvm4WuYxTiGkRagRqHUey0meRQL.jpg",
    release_date: "2002-11-06",
    title: "Spider",
    video: false,
    vote_average: 6.6,
    vote_count: 924,
  },
  {
    adult: false,
    backdrop_path: "/6fKEw0I2FTD5FLOQ5q7L1tqf876.jpg",
    genre_ids: [10751, 35, 12, 878],
    id: 790493,
    original_language: "en",
    original_title: "Spy Kids: Armageddon",
    overview:
      "When the children of the world’s greatest secret agents unwittingly help a powerful game developer unleash a computer virus that gives him control of all technology, they must become spies themselves to save their parents and the world.",
    popularity: 2.491,
    poster_path: "/vd8YdaH7dzeIMGTNwQinlSiA1gV.jpg",
    release_date: "2023-09-22",
    title: "Spy Kids: Armageddon",
    video: false,
    vote_average: 6,
    vote_count: 168,
  },
  {
    adult: false,
    backdrop_path: "/zZEJu3db4Ld4urK5klPvQxkWzaX.jpg",
    genre_ids: [12, 14, 18, 35, 10402],
    id: 6116,
    original_language: "en",
    original_title: "Spice World",
    overview:
      "World famous pop group the Spice Girls zip around London in their luxurious double decker tour bus having various adventures and performing for their fans.",
    popularity: 2.5111,
    poster_path: "/vKiAnV1QAGIJP38vatwCZp4dCrH.jpg",
    release_date: "1997-12-18",
    title: "Spice World",
    video: false,
    vote_average: 4.9,
    vote_count: 501,
  },
  {
    adult: false,
    backdrop_path: "/zEuXnDVLny3CHdoSk3WpvCsRyZD.jpg",
    genre_ids: [35, 10402],
    id: 975225,
    original_language: "en",
    original_title: "Spinal Tap II: The End Continues",
    overview:
      "The now estranged bandmates of Spinal Tap are forced to reunite for one final concert, hoping it will solidify their place in the pantheon of rock 'n' roll.",
    popularity: 2.3306,
    poster_path: "/c8Vg1HOlAN8pNPkUrH7Mov1KOLk.jpg",
    release_date: "2025-09-12",
    title: "Spinal Tap II: The End Continues",
    video: false,
    vote_average: 6.377,
    vote_count: 77,
  },
  {
    adult: false,
    backdrop_path: "/xOqg1A4dUqYbjhzhchSgSpaXdYk.jpg",
    genre_ids: [18, 10752, 53],
    id: 688301,
    original_language: "ja",
    original_title: "スパイの妻",
    overview:
      "It’s 1940, and the population of Japan is divided over its entry into World War II. Satoko, the wife of a fabric merchant, is devoted to her husband but is beginning to suspect he’s up to something. Soon she allows herself to be drawn into a game in which she enigmatically conceals her intentions.",
    popularity: 2.4677,
    poster_path: "/seFjT7jDZA1j1YsbMyeNTuCRe5d.jpg",
    release_date: "2020-10-16",
    title: "Wife of a Spy",
    video: false,
    vote_average: 6.7,
    vote_count: 99,
  },
  {
    adult: false,
    backdrop_path: "/9RJGN6CaCFOzs9H1yie2aPxLUoX.jpg",
    genre_ids: [35, 12],
    id: 9080,
    original_language: "en",
    original_title: "Spies Like Us",
    overview:
      "Two bumbling government employees think they are U.S. spies, only to discover that they are actually decoys for nuclear war.",
    popularity: 1.5368,
    poster_path: "/s0Sx8nd9Irq0aCPbsN78s0DYVlG.jpg",
    release_date: "1985-12-06",
    title: "Spies Like Us",
    video: false,
    vote_average: 6.188,
    vote_count: 693,
  },
  {
    adult: false,
    backdrop_path: "/fAiadlNo44vVLagveGa51O4soRB.jpg",
    genre_ids: [53, 18, 36],
    id: 616558,
    original_language: "no",
    original_title: "Spionen",
    overview:
      "Sonja Wigert, Scandinavia's most acclaimed female movie star, enlists as a spy for Swedish intelligence but ends up becoming entangled with the German Reichskommissar Terboven.",
    popularity: 1.6986,
    poster_path: "/cJdrqRggDs6t5iKTsmg7XwViWE0.jpg",
    release_date: "2019-10-18",
    title: "The Spy",
    video: false,
    vote_average: 6.1,
    vote_count: 79,
  },
];

export const movieDetailFixture = {
  id: 640146,
  title: "앤트맨과 와스프: 퀀텀매니아",
  poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
  overview:
    "슈퍼히어로 파트너인 스캇 랭과 호프 반 다인, 호프의 부모 재닛 반 다인과 행크 핌, 그리고 스캇의 딸 캐시 랭까지 미지의 양자 영역 세계 속에 빠져버린 앤트맨 패밀리. 그 곳에서 새로운 존재들과 무한한 우주를 다스리는 정복자 캉을 만나며, 그 누구도 예상 못 한 모든 것의 한계를 뛰어넘는 모험을 시작하게 되는데…",
  release_date: "2023-02-15",
  vote_average: 6.232,
  genres: [
    {
      id: 28,
      name: "액션",
    },
    {
      id: 12,
      name: "모험",
    },
    {
      id: 878,
      name: "SF",
    },
  ],
};
