import { MovieResponse } from '../types/Movie.types';

export const MOVIE_RESPONSE: MovieResponse = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/nhjXe1Gb3Hq8Q5COjsY7ehZyJl4.jpg',
      genre_ids: [18, 35, 53, 28],
      id: 1438267,
      original_language: 'he',
      original_title: 'גמד מחמד 4',
      overview:
        "Four years have passed since Kfar and Gamadi's last fight, which ended in Gamadi's defeat. As time passes, the neverending threat of Gamadi seems to haunt Kfar, and leads him into a life revolving around the constant seek of revenge, violence and hate. And now with Piggy, his best friend, leaving to join the army. Kfar is left to deal with Gamadi on his own.",
      popularity: 13.754,
      poster_path: '/9jw0tNgP3pRCq3WioDDbjwOI1n4.jpg',
      release_date: '2025-03-16',
      title: 'Gamad Machmad 4',
      video: false,
      vote_average: 4.167,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1439526,
      original_language: 'en',
      original_title: 'Full Out',
      overview:
        'In 19th-century Paris at the Salpêtrière Hospital, patients were hypnotized onstage to reproduce the symptoms of hysteria for public audiences. Over a century later, high school cheerleaders are fainting en masse.',
      popularity: 13.753,

      poster_path: '/eXvVjE5RyNKbxHCmmj1DLu55GKe.jpg',
      release_date: '2025-03-16',
      title: 'Full Out',
      video: false,
      vote_average: 4.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1439514,
      original_language: 'en',
      original_title: 'The Phalanx',
      overview:
        'Letters from the Ceresco community trace the fragility of harmony, the dream of life in association. Members of the phalanx drift apart, lingering in private corners, suspended in speculative time.',
      popularity: 13.753,
      poster_path: '/4wgiJBrpvLh9kOe8feXd5MxLbzW.jpg',
      release_date: '2025-03-16',
      title: 'The Phalanx',
      video: false,
      vote_average: 4.333,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: '/3IcE36HHehBWHDRXSoEQ6hl5ei8.jpg',
      genre_ids: [18],
      id: 1440083,
      original_language: 'es',
      original_title: 'Marciano García',
      overview: '',
      popularity: 13.471,
      poster_path: '/sdGwrjlFO9NII5mPKf57kCjX9VD.jpg',
      release_date: '2025-03-16',
      title: 'Marciano García',
      video: false,
      vote_average: 5.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: '/cShaLua5ZlSGlP5esqsJ1dTBrWi.jpg',
      genre_ids: [18, 36],
      id: 1442915,
      original_language: 'bg',
      original_title: 'Залог',
      overview:
        'Before the Liberation, during the years of the exiled Bulgarian revolutionaries in Romania, the Major and the Prime Minister once shared the same ideals, the same home, and even the same woman. Today, the Major orchestrates a conspiracy to overthrow the government led by his former friend, the Prime Minister. The head of state must be assassinated, and the Prince – dethroned. The woman is part of the plot, but she will try to prevent the fratricide.',
      popularity: 13.469,
      poster_path: '/aqsDDMTnmTZwbbZmDepqLFPdoiZ.jpg',
      release_date: '2025-03-16',
      title: 'Bet',
      video: false,
      vote_average: 7,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 1443480,
      original_language: 'de',
      original_title: 'Der geräderte Mensch',
      overview: '',
      popularity: 13.468,
      poster_path: '/4gQ2ZnfZ6u6WB9iWmWm9sLCLqm1.jpg',
      release_date: '2025-03-16',
      title: 'Der geräderte Mensch',
      video: false,
      vote_average: 4,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1444331,
      original_language: 'es',
      original_title: 'Final',
      overview:
        'One room, two girls. They would be the perfect elements for a new sapphic love story, except for Alex and Pau, which is the end of it all. Both try to , but this was never synonymous with easy.',
      popularity: 13.456,
      poster_path: '/nSNOzbstoR0dW960oT1c33qGiYz.jpg',
      release_date: '2025-03-16',
      title: 'Final',
      video: false,
      vote_average: 4.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: '/m4FEubjmtytpMDchQfDmbJKHOG6.jpg',
      genre_ids: [99],
      id: 1437446,
      original_language: 'en',
      original_title: 'The Twister: Caught in the Storm',
      overview:
        'In May 2011, a massive tornado ripped through Joplin, Missouri. With pulse-pounding firsthand footage, this documentary goes inside a deadly twister.',
      popularity: 21.162,
      poster_path: '/ggXb37lX9gW4SR7kpMaraXDFeFR.jpg',
      release_date: '2025-03-18',
      title: 'The Twister: Caught in the Storm',
      video: false,
      vote_average: 7,
      vote_count: 1,
    },
  ],
  total_pages: 49237,
  total_results: 984732,
};
