export const ELEMENT_SELECTOR = {
  app: '#app',
  main: 'main',
  movieReviewDetailModal: '#movie-review-detail-modal',
  modalReviewDetailHeader: '#modal-review-detail-header',
  modalCloseButton: '#modal-close-button',
  errorFallBackModal: '#error-fallback-modal',
  reloadButton: '#reload-button',
  movieReviewSection: '#movie-review-section',
  searchForm: '#search-form',
  searchInput: '#search-input',
  movieLogo: '#movie-logo',
  movieListContainer: '#movie-list-container',
  itemCard: '#item-card',
  modalReviewDetailSection: '#modal-review-detail-section',
  movieScoreBoardRating: '#movie-score-board-rating',
  movieScoreBoardNeedRating: '#movie-score-board-need-rating',
  movieScoreBoardImage: '#movie-score-board-stars>img',
  movieScoreBoardStars: '#movie-score-board-stars',
  observerTarget: '#observer-target',
} as const;
