const POPULAR_MOVIE_DATA = {
  PAGE1: [
    {
      adult: false,
      backdrop_path: '/2Eewgp7o5AU1xCataDmiIL2nYxd.jpg',
      genre_ids: [18, 36],
      id: 943822,
      original_language: 'en',
      original_title: 'Prizefighter: The Life of Jem Belcher',
      overview: '',
      popularity: 2446.928,
      poster_path: '/x3PIk93PTbxT88ohfeb26L1VpZw.jpg',
      release_date: '2022-06-30',
      title: 'Prizefighter: The Life of Jem Belcher',
      video: false,
      vote_average: 7,
      vote_count: 42,
    },
    {
      adult: false,
      backdrop_path: '/r7Dfg9aRZ78gJsmDlCirIIlNH3d.jpg',
      genre_ids: [18],
      id: 785084,
      original_language: 'en',
      original_title: 'The Whale',
      overview:
        '272kg의 거구로 세상을 거부한 채 살아가는 대학 강사 찰리는 남은 시간이 얼마 없음을 느끼고 오랫동안 만나지 못한 10대 딸 엘리를 집으로 초대한다. 그리고, 매일 자신을 찾아와 에세이 한 편을 완성하면 전 재산을 주겠다고 제안한다.',
      popularity: 1635.863,
      poster_path: '/q0xV5Lnq30JiegbVGBOvVwrgUDT.jpg',
      release_date: '2022-12-09',
      title: '더 웨일',
      video: false,
      vote_average: 8.1,
      vote_count: 1262,
    },
    {
      adult: false,
      backdrop_path: '/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg',
      genre_ids: [16, 12, 35, 10751],
      id: 315162,
      original_language: 'en',
      original_title: 'Puss in Boots: The Last Wish',
      overview:
        "아홉 개의 목숨 중 단 하나의 목숨만 남은 장화신은 고양이.  마지막 남은 목숨을 지키기 위해 히어로의 삶 대신 반려묘의 삶을 선택한 그에게 찾아온 마지막 기회, 바로 소원을 들어주는 소원별이 있는 곳을 알려주는 지도!  잃어버린 목숨을 되찾고 다시 히어로가 되기를 꿈꾸는 장화신은 고양이는 뜻밖에 동료가 된 앙숙 파트너 '키티 말랑손', 그저 친구들과 함께라면 모든 게 행복한 강아지 '페로'와 함께 소원별을 찾기 위해 길을 떠난다.  그리고 소원별을 노리는 또 다른 빌런들과 마주치게 되는데…",
      popularity: 1943.595,
      poster_path: '/rKgvctIuPXyuqOzCQ16VGdnHxKx.jpg',
      release_date: '2022-12-07',
      title: '장화신은 고양이: 끝내주는 모험',
      video: false,
      vote_average: 8.4,
      vote_count: 4630,
    },
    {
      adult: false,
      backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
      genre_ids: [28, 12, 878],
      id: 505642,
      original_language: 'en',
      original_title: 'Black Panther: Wakanda Forever',
      overview:
        '국왕이자 블랙 팬서인 티찰라의 죽음 이후 수많은 강대국으로부터 위협을 받게 된 와칸다. 라몬다, 슈리 그리고 나키아, 오코예, 음바쿠는 각자 사명감을 갖고 와칸다를 지키기 위해 외로운 싸움을 이어간다. 한편, 비브라늄의 패권을 둘러싼 미스터리한 음모와 함께 깊은 해저에서 모습을 드러낸 최강의 적 네이머와 탈로칸의 전사들은 와칸다를 향해 무차별 공격을 퍼붓기 시작하는데…',
      popularity: 1671.218,
      poster_path: '/3PCRWLeqp5y20k6XVzcamZR3BWF.jpg',
      release_date: '2022-11-09',
      title: '블랙 팬서: 와칸다 포에버',
      video: false,
      vote_average: 7.3,
      vote_count: 4111,
    },
    {
      adult: false,
      backdrop_path: '/22z44LPkMyf5nyyXvv8qQLsbom.jpg',
      genre_ids: [27, 9648, 53],
      id: 631842,
      original_language: 'en',
      original_title: 'Knock at the Cabin',
      overview:
        '휴가를 떠난 한 가족은 별장에 무단침입한 낯선 방문자들과 대치하게 된다. ‘레너드’(데이브 바티스타)와 낯선 방문자들은 세상의 종말을 막으러 왔다며, 가족 중 한 명을 희생시켜야만 인류의 멸망을 막을 수 있다는 잔혹한 선택을 하게 하는데… 가족을 살리면 인류가 멸망하고, 인류를 살리면 가족이 죽는다!',
      popularity: 1514.423,
      poster_path: '/mCDSOfcVJfMkGUNrNpXWFO7oNBY.jpg',
      release_date: '2023-02-01',
      title: '똑똑똑',
      video: false,
      vote_average: 6.4,
      vote_count: 1021,
    },
  ],
  PAGE2: [
    {
      adult: false,
      backdrop_path: '/A2avUoNFstnBhAnHiogXQs4c9Bt.jpg',
      genre_ids: [18, 27, 9648],
      id: 772515,
      original_language: 'es',
      original_title: 'Huesera',
      overview:
        "Valeria's joy at becoming a first-time mother is quickly taken away when she's cursed by a sinister entity. As danger closes in, she's forced deeper into a chilling world of dark magic that threatens to consume her.",
      popularity: 656.767,
      poster_path: '/zgpj76z9byUgcWnxLDmtZ3XqfvN.jpg',
      release_date: '2023-02-10',
      title: 'Huesera: The Bone Woman',
      video: false,
      vote_average: 5.8,
      vote_count: 142,
    },
    {
      adult: false,
      backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
      genre_ids: [28, 14, 878],
      id: 436270,
      original_language: 'en',
      original_title: 'Black Adam',
      overview:
        'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
      popularity: 693.987,
      poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
      release_date: '2022-10-19',
      title: 'Black Adam',
      video: false,
      vote_average: 7.1,
      vote_count: 4465,
    },
    {
      adult: false,
      backdrop_path: '/nDg8feBTHh52YCAuXpFWynznqAh.jpg',
      genre_ids: [53, 28],
      id: 850871,
      original_language: 'es',
      original_title: 'Sayen',
      overview:
        "Sayen is hunting down the men who murdered her grandmother. Using her training and knowledge of nature, she is able to turn the tables on them, learning of a conspiracy from a corporation that threatens her people's ancestral lands.",
      popularity: 918.47,
      poster_path: '/aCy61aU7BMG7SfhkaAaasS0KzUO.jpg',
      release_date: '2023-03-03',
      title: 'Sayen',
      video: false,
      vote_average: 6.8,
      vote_count: 33,
    },
    {
      adult: false,
      backdrop_path: '/mqsPyyeDCBAghXyjbw4TfEYwljw.jpg',
      genre_ids: [18, 10752, 36],
      id: 49046,
      original_language: 'de',
      original_title: 'Im Westen nichts Neues',
      overview:
        'Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.',
      popularity: 495.474,
      poster_path: '/hYqOjJ7Gh1fbqXrxlIao1g8ZehF.jpg',
      release_date: '2022-10-07',
      title: 'All Quiet on the Western Front',
      video: false,
      vote_average: 7.8,
      vote_count: 2219,
    },
    {
      adult: false,
      backdrop_path: '/kQW6UMeIfuDmYV6Dse9uKIu3IKg.jpg',
      genre_ids: [9648, 53, 27],
      id: 782936,
      original_language: 'en',
      original_title: 'Nocebo',
      overview:
        'A fashion designer hires a nanny from the Philippines to assist her in caring for her family while she is suffering from what she believes is a tick-related illness. The nanny uses traditional Filipino folk healing techniques to help her, but in the process of doing so, she uncovers a horrifying truth about why she is there and why her employer is actually sick.',
      popularity: 561.228,
      poster_path: '/3FPnDTlX0LsaU4VD5mc82BMbchA.jpg',
      release_date: '2022-11-03',
      title: 'Nocebo',
      video: false,
      vote_average: 6.4,
      vote_count: 48,
    },
  ],
};

const POPULAR_MOVIE_MAPPED_DATA = {
  PAGE1: [
    {
      id: 943822,
      poster_path: '/x3PIk93PTbxT88ohfeb26L1VpZw.jpg',
      title: 'Prizefighter: The Life of Jem Belcher',
      vote_average: 7,
    },
    {
      id: 785084,
      poster_path: '/q0xV5Lnq30JiegbVGBOvVwrgUDT.jpg',
      title: '더 웨일',
      vote_average: 8.1,
    },
    {
      id: 315162,
      poster_path: '/rKgvctIuPXyuqOzCQ16VGdnHxKx.jpg',
      title: '장화신은 고양이: 끝내주는 모험',
      vote_average: 8.4,
    },
    {
      id: 505642,
      poster_path: '/3PCRWLeqp5y20k6XVzcamZR3BWF.jpg',
      title: '블랙 팬서: 와칸다 포에버',
      vote_average: 7.3,
    },
    {
      id: 631842,
      poster_path: '/mCDSOfcVJfMkGUNrNpXWFO7oNBY.jpg',
      title: '똑똑똑',
      vote_average: 6.4,
    },
  ],
  PAGE2: [
    {
      id: 772515,
      poster_path: '/zgpj76z9byUgcWnxLDmtZ3XqfvN.jpg',
      title: 'Huesera: The Bone Woman',
      vote_average: 5.8,
    },
    {
      id: 436270,
      poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
      title: 'Black Adam',
      vote_average: 7.1,
    },
    {
      id: 850871,
      poster_path: '/aCy61aU7BMG7SfhkaAaasS0KzUO.jpg',
      title: 'Sayen',
      vote_average: 6.8,
    },
    {
      id: 49046,
      poster_path: '/hYqOjJ7Gh1fbqXrxlIao1g8ZehF.jpg',
      title: 'All Quiet on the Western Front',
      vote_average: 7.8,
    },
    {
      id: 782936,
      poster_path: '/3FPnDTlX0LsaU4VD5mc82BMbchA.jpg',
      title: 'Nocebo',
      vote_average: 6.4,
    },
  ],
};

export { POPULAR_MOVIE_DATA, POPULAR_MOVIE_MAPPED_DATA };
