const SEARCHED_MOVIE_DATA = {
  PAGE1: [
    {
      adult: false,
      backdropPath: '/kl3rMfydlxyLDsZidSUCEWm8K0M.jpg',
      genreIds: [12, 35, 878],
      id: 39513,
      originalLanguage: 'en',
      originalTitle: 'Paul',
      overview:
        "외계인과 SF를 좋아하는 절친한 괴짜 그램과 클라이브는 SF 코믹콘 행사에 참여하기 위해 미국 여행길에 오른다.  코믹콘 행사 이후 SF 매니아들 사이에서는 외계인 성지 순례길이라고 불리우는 UFO의 메카, 외계인 연구 비밀 구역 ‘에이리어 51’구역까지 찾아간 두 남자.  오마이 갓뜨! 그 곳에서 그들이 한 평생 꿈에만 그리던 진짜 외계인을 만나게 되는데 지구에 온 지 60년이 된 ‘폴'이라는 이름을 가진 그는 음주가무과 음담패설을 즐기며 외계인 포스라고는 전혀 찾아볼 수 없다. 우주선을 타고 탐사를 나왔다가 60년 전에 사고로 지구에 혼자 남게 되고 그 동안 미국의 정부와 영화 산업에 많은 일을 하며 지냈다는 폴이 자신의 목숨이 위험하다며 그들에게 도움을 요청한다. 반신반의로 ‘폴’을 도울 수 밖에 없게 된 그램과 클라이브. 폴을 이용해서 한 몫을 챙기려는 이들로부터 쫓고 쫓기는 사상 최대의 글로벌 추격전이 시작된다!",
      popularity: 44.317,
      posterPath: '/sCg1Ikv0yNNzq208pl16qjBMInA.jpg',
      releaseDate: '2011-02-14',
      title: '황당한 외계인: 폴',
      video: false,
      voteAverage: 6.7,
      voteCount: 5085,
    },
    {
      adult: false,
      backdropPath: '/30Z4DjbSJEW9oZv4hAksiAmji7r.jpg',
      genreIds: [35, 27, 878],
      id: 16296,
      originalLanguage: 'en',
      originalTitle: 'Killer Klowns from Outer Space',
      overview:
        '삐에로처럼 생긴 외계인들이 마을에 나타나 사람들을 납치해 솜사탕으로 만들어 먹는다. 마을의 젊은이들은 위험을 깨닫지만, 다른 마을 사람들은 일을 심각하게 여기지 않고 그들의 말을 믿지 않는다.',
      popularity: 22.536,
      posterPath: '/gkgqtr2weef0sUM3k1mFe52iola.jpg',
      releaseDate: '1988-05-27',
      title: '외계인 삐에로',
      video: false,
      voteAverage: 6.411,
      voteCount: 768,
    },
    {
      adult: false,
      backdropPath: '/zsqfhpnl4sZ3aGUufJUsNDxXXZv.jpg',
      genreIds: [12, 35, 10751, 14, 878],
      id: 20856,
      originalLanguage: 'en',
      originalTitle: 'Aliens in the Attic',
      overview:
        '아빠 스튜어트와 엄마 니나, 그리고 장녀 베타니, 15살 장남 톰, 그리고 7살 막내 한나로 이루어진 피어슨 가족은 네이트 삼촌의 가족과 함께, 메인 주에 위치한 3층짜리 별장으로 여름 휴가를 떠난다. 하지만, 이들에 앞서 별장을 점거하고 있는 이들이 있었으니, 키가 보통사람의 무릎까지 오는 난쟁이 외계인들이 그들이다. 이 외계인들은 겉보기에는 사람들에게 무해한 것처럼 보이지만, 인간들을 자기 마음대로 조종할 수 있는 무시무시한 기술을 가진 생명체. 틴에이저인 톰과 사촌 제이크 등은 부모님과 이웃사람들, 그리고 나아가서는 지구를 지키기 위해 외계인들에게 과감히 맞서는데...',
      popularity: 18.462,
      posterPath: '/gjDfPcKcxdJlJkK6pgHrwDfSG3O.jpg',
      releaseDate: '2009-07-31',
      title: '다락방의 외계인',
      video: false,
      voteAverage: 5.657,
      voteCount: 887,
    },
    {
      adult: false,
      backdropPath: '/AgYlP6g4vrNn1sVsAIvflW3TfJU.jpg',
      genreIds: [35, 16, 10751],
      id: 422803,
      originalLanguage: 'en',
      originalTitle: 'A Shaun the Sheep Movie: Farmageddon',
      overview:
        '머~언 우주에서 길을 잃고 지구에 오게 된 꼬마 외계인 ‘룰라’! 우연히 양떼목장의 비글비글 사고뭉치들 ‘숀’과 친구들을 만난다. 달콤한 젤리와 초콜릿이 가득한 지구에서 즐거운 시간을 보내지만 엄마 아빠가 보고 싶은 ‘룰라’를 위해 집을 찾아 주기로 하는 ‘숀’과 친구들! 우주에 가기 위해 ‘룰라’가 잃어버린 UFO를 찾아 나서고 한편 수상한 비밀요원 ‘에이전트 레드’ 일당이 ‘룰라’를 추적하는데… 과연, ‘룰라’는 무사히 엄마 아빠 곁으로 돌아갈 수 있을까?',
      popularity: 15.013,
      posterPath: '/oUvRqxUmxNXMndQ1tTKDttVz3z1.jpg',
      releaseDate: '2019-09-26',
      title: '숀더쉽 더 무비: 꼬마 외계인 룰라!',
      video: false,
      voteAverage: 6.9,
      voteCount: 414,
    },
    {
      adult: false,
      backdropPath: '/ufEfaCjO8KDFk1frQbueoVd1s8z.jpg',
      genreIds: [35, 878],
      id: 12120,
      originalLanguage: 'en',
      originalTitle: 'My Stepmother Is an Alien',
      overview:
        '어린 딸(Jessie Mills: 알리슨 해니건 분)과 함께 사는 외로운 과학자 스티브(Steven Mills: 댄 애크로이드 분)는 순전히 호기심으로 레이저 광선을 발사한다. 그런데 지구에서 90억 광년 떨어진 혹성에서 이 광선을 받고, 조사를 위해 외계인 셀레스터(Celeste Martin: 킴 베신져 분)가 지구로 온다. 파티장에 나타난 셀레스터는 지구의 관습을 몰라 실수 연발하지만, 스티브는 이 아름다운 외계인에게 한눈에 반한다. 셀레스터는 결혼, 사랑 등 알 수 없는 단어들을 체험하기 위해 스티브와 결혼한다. 어느 날 스티브의 어린 딸이 셀레스터가 전기 배터리로 식사하는 것을 보자 셀레스터를 조정하는 우주 특사는 딸을 죽이라고 한다. 그러나 이미 지구인이 되다시피한 셀레스터는 갈팡질팡 한다. 그리고 그녀를 데리러온 우주선을 향해 스티브와 함께 지구에서 살겠다고 외친다.',
      popularity: 12.681,
      posterPath: '/o9feh3DGHvNZ835cm2ajYHwZwiN.jpg',
      releaseDate: '1988-12-09',
      title: '새 엄마는 외계인',
      video: false,
      voteAverage: 5.727,
      voteCount: 442,
    },
  ],
  PAGE2: [
    {
      adult: false,
      backdropPath: '/me5RPIQEtv0qpjlKQlb1SLijVVU.jpg',
      genreIds: [53, 35, 27],
      id: 12416,
      originalLanguage: 'da',
      originalTitle: 'Vikaren',
      overview:
        '6학년 학급을 새로 맡은 여선생님. 그런데 뭔가 이상하다. 선생님이 아이들 하나하나의 마음을 모두 읽어내는 것. 그렇다. 선생님은 바로 외계인이었던 것이다. 그런데 어떻게 엄마 아빠는 그녀가 너무나 좋은 선생님이라고 생각하는 것일까? 에일리언 선생님, 그냥 두고 볼 수만은 없어! 2007년 덴마크 최고 흥행작.',
      popularity: 5.143,
      posterPath: '/zHApRXaV1NckNtZh6PnKChie2l1.jpg',
      releaseDate: '2007-03-13',
      title: '선생님은 외계인',
      video: false,
      voteAverage: 5.491,
      voteCount: 54,
    },
    {
      adult: false,
      backdropPath: '/g10IQmMVbybootpK8NGKIFZthSZ.jpg',
      genreIds: [878, 35, 28],
      id: 660267,
      originalLanguage: 'no',
      originalTitle: 'Blasted: Gutta vs Aliens',
      overview:
        '외계인 침공이 총각 파티를 방해하자 소꿉친구 둘이 예전처럼 다시 최강의 레이저 태그 콤비를 이루어 반격에 나선다.',
      popularity: 5.905,
      posterPath: '/swvs2aIf2aSSrcvfSQGy8c9N5Tb.jpg',
      releaseDate: '2022-06-28',
      title: '블래스티드: 친구들 vs 외계인',
      video: false,
      voteAverage: 4.691,
      voteCount: 47,
    },
    {
      adult: false,
      backdropPath: '/gNfqcj4vBpyobooCXXDB5n11WtE.jpg',
      genreIds: [10751, 878, 12],
      id: 31397,
      originalLanguage: 'en',
      originalTitle: 'Alien from L.A.',
      overview:
        'When her archaeologist father disappears on an expedition, Wanda sets out to look for him. What she finds is a secret underground world, where no one believes in life on the surface and where she and her father are taken for spies.',
      popularity: 4.846,
      posterPath: '/4JhRbIS4cfsOog1ZrjJsRNvIHZG.jpg',
      releaseDate: '1988-02-26',
      title: 'LA에서 온 외계인',
      video: false,
      voteAverage: 2.947,
      voteCount: 47,
    },
    {
      adult: false,
      backdropPath: '/kPWABfYVotvqMxJnw8D7Nr6PQUL.jpg',
      genreIds: [27],
      id: 505063,
      originalLanguage: 'en',
      originalTitle: 'Await Further Instructions',
      overview:
        '아버지와 관계가 소원한 샘은 크리스마스를 맞아 여자친구 앤지를 데리고 몇 년 만에 집을 찾아온다. 가족들은 아시아계인 앤지에 대한 편견으로 갈등을 일으키지만 크리스마스가 되자 의문의 검은 물질이 집 주변을 완전히 뒤덮는 바람에 꼼짝없이 갇히고 만다. 모든 통신이 끊어진 상태에서 그들을 바깥 세상과 연결해주는 것은 오직 TV에 나오는 믿기 어려운 메시지뿐인데.',
      popularity: 10.23,
      posterPath: '/afvi5tVi5S3Ux9faZaI32SmPRkj.jpg',
      releaseDate: '2018-08-26',
      title: '인류멸망 : 외계인이 주는 마지막 기회',
      video: false,
      voteAverage: 5.4,
      voteCount: 226,
    },
    {
      adult: false,
      backdropPath: '/5nJ9hK8rPS5SaHtq8JbMGny1qvR.jpg',
      genreIds: [878, 27, 35],
      id: 468091,
      originalLanguage: 'en',
      originalTitle: 'Alien Invasion',
      overview:
        '특종을 위해 외계인이 목격된 마을로 향한 기자 ‘세라’는  마을의 보안관 ‘조’와 함께 한 병영을 조사하기 시작한다.  그러나, 정체를 알 수 없는 괴생명체로부터 갑작스러운 공격을 받게 되고 다행히 병영 관리인 ‘에드’의 도움으로 상처를 치료한다. 한편, ‘에드’는 괴생명체를 처치하기 위해 갑자기 사라져 버리고, ‘조’는 그런 ‘에드’를 찾기 위해 자리를 비우면서 ‘세라’는 홀로 남게 된다.  그 때, 주변에서 그녀를 노리는 누군가의 인기척이 느껴지고 그것이 괴생명체임을 직감한 ‘세라’는 두려움에 떨기 시작하는데…',
      popularity: 3.453,
      posterPath: '/z6mDbSOKLDC0xXDaOm3Fdo4nSgA.jpg',
      releaseDate: '2018-11-14',
      title: '외계인 지구침공',
      video: false,
      voteAverage: 3.4,
      voteCount: 20,
    },
  ],
};

const SEARCHED_MOVIE_MAPPED_DATA = {
  PAGE1: [
    {
      id: 39513,
      posterPath: '/sCg1Ikv0yNNzq208pl16qjBMInA.jpg',
      title: '황당한 외계인: 폴',
      voteAverage: 6.7,
    },
    {
      id: 16296,
      posterPath: '/gkgqtr2weef0sUM3k1mFe52iola.jpg',
      title: '외계인 삐에로',
      voteAverage: 6.4,
    },
    {
      id: 20856,
      posterPath: '/gjDfPcKcxdJlJkK6pgHrwDfSG3O.jpg',
      title: '다락방의 외계인',
      voteAverage: 5.7,
    },
    {
      id: 422803,
      posterPath: '/oUvRqxUmxNXMndQ1tTKDttVz3z1.jpg',
      title: '숀더쉽 더 무비: 꼬마 외계인 룰라!',
      voteAverage: 6.9,
    },
    {
      id: 12120,
      posterPath: '/o9feh3DGHvNZ835cm2ajYHwZwiN.jpg',
      title: '새 엄마는 외계인',
      voteAverage: 5.7,
    },
  ],
  PAGE2: [
    {
      id: 12416,
      posterPath: '/zHApRXaV1NckNtZh6PnKChie2l1.jpg',
      title: '선생님은 외계인',
      voteAverage: 5.5,
    },
    {
      id: 660267,
      posterPath: '/swvs2aIf2aSSrcvfSQGy8c9N5Tb.jpg',
      title: '블래스티드: 친구들 vs 외계인',
      voteAverage: 4.7,
    },
    {
      id: 31397,
      posterPath: '/4JhRbIS4cfsOog1ZrjJsRNvIHZG.jpg',
      title: 'LA에서 온 외계인',
      voteAverage: 2.9,
    },
    {
      id: 505063,
      posterPath: '/afvi5tVi5S3Ux9faZaI32SmPRkj.jpg',
      title: '인류멸망 : 외계인이 주는 마지막 기회',
      voteAverage: 5.4,
    },
    {
      id: 468091,
      posterPath: '/z6mDbSOKLDC0xXDaOm3Fdo4nSgA.jpg',
      title: '외계인 지구침공',
      voteAverage: 3.4,
    },
  ],
};

export { SEARCHED_MOVIE_DATA, SEARCHED_MOVIE_MAPPED_DATA };
